apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pharma
type: Opaque
stringData:
  DB_HOST: pharma-dev-postgres.c8zsmesiuilk.us-east-1.rds.amazonaws.com
  DB_NAME: pharmadb
  DB_USER: pharmaadmin
  DB_PASSWORD: YourStrongPassword123!