name: Runner Test

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: crud-backend
  ACCOUNT_ID: "076124125794"

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          echo "Runner is working"
          hostname
          whoami
          pwd

      - name: Check Docker
        run: docker --version

      - name: Check AWS CLI
        run: aws --version
